language: rust
rust:
  - stable
  - beta
  - nightly
before_install: 
  - sudo apt-get -qq update
  - sudo apt-get install -y  openssl libssl-dev libbz2-dev zlib1g-dev ffmpeg yasm
#cache: cargo
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo test --features partially-static,transcoding-cache,behind-proxy
  - cargo test --no-default-features --features partially-static --workspace
  - if [[ "$TRAVIS_RUST_VERSION" = "stable" ]]; then cargo test --features partially-static,transcoding-cache  --test test_binary -- --ignored; fi
matrix:
  fast_finish: true
  allow_failures:
  - rust: nightly
  include:
    - language: node_js
      before_script: true
      node_js: "10"
      cache:
        directories:
        - "client/node_modules"
      script:
      - cd client
      - npm install
      - npm run build
    - language: minimal
      if: tag IS present
      before_install: true
      before_script: true
      script: true
      services:
        - docker
      deploy:
        - provider: script
          on:
            branch: master
            tags: true
          script: bash docker_push.sh
    - language: minimal
      if: tag IS present
      before_install: true
      services:
        - docker
      before_script: true
      script: 
        - ./build_static.sh
      deploy:
        - provider: releases
          on:
            branch: master
            tags: true
          api_key:
            secure: NlP+bkwDihtgjWUG0GYT2Ywebon6X1uA6T1ddY/JhmkQ8uoF7+XXQ23jIsu1MOCXHMhzyRlZ2HO5AetNkc6tlBa5qUF3eQNkpYz0CuxQnhjGVqt4UrUBNweqKomavcYxumeiXYtVazpCoSLcRlLAgzaCf1H4KVZSIJTvEIeo1D4+zrFbsG4Fr46M9IRsaQkaVrkYijeaYw3qd5Q1KhdCyeIv5sqQEo7UCDdM+aLryaq7K0FhTAeM84PmYQCYLxWx2zEQ4vl4uHeWkWLeA3kHss/dmhdnZhTVThGLVjtPfzyFIcssy9Buf5B635o05hl2OaETi7AJoG8izD/+gNsd451asTGvuYgn30uKIzy7zrVHXM1D67+rTZoAM48aqC4g99QwIrkiNITI8qlwp7OTjnsgWvyZZgMqGVfdFVvYDAmPggRDrjBFIbApXYDJ6koJvxGb4Vb4qcObNRgxhGeIT78CrX4fsfAoQWHRCj592V3U4hU6xnbRBrf2brfbA+nLKAjJ5cXYQLDciB8EeA7GmSvASJLPBwtsDWiq3IsJQK8RAUiaWoE934YphwPY/WUk0oVRCOgBuh/4YyjGyxUQtknKhXj6+G9D1Tja1z/fiGHnrx32C+CxXAxnZ94LS1AWDX+KE/D3mw4fHbWJVF4jtVxNdskxs6BZMtcxAVDYweY=
          file: _static_build/audioserve_static.tar.gz
          skip_cleanup: true


