FROM alpine:edge AS build
MAINTAINER Ivan <ivan@zderadicka.eu>

ARG FEATURES

RUN apk update &&\
    apk add git bash openssl openssl-dev taglib taglib-dev curl yasm build-base \
    wget libbz2 bzip2-dev  zlib zlib-dev rust cargo ffmpeg &&\
    adduser -D -H -u 1000 ivan &&\
    mkdir /src

USER ivan   
WORKDIR /src
ENV RUSTFLAGS="-C target-feature=+crt-static"
CMD  cargo build --target x86_64-alpine-linux-musl --release ${FEATURES}




