[package]
name = "async-tar"
version = "0.1.1"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

[dependencies]
tar="0.4"
futures="0.3"
tokio={version="1.2", features=["fs"]}

[dev-dependencies]
tempfile="3.2"
tokio-util = {version="0.6", features=["codec"]}
tokio={version="1.2", features=["macros", "rt"]}

