[package]
name = "websock"
version = "0.3.0"
authors = ["Ivan <ivan.zderadicka@gmail.com>"]
edition = "2018"

[dependencies]

hyper = "0.14"
tokio = {version="1.2", features=["rt-multi-thread", "time"]}
futures = "0.3"
log = {version="0.4", features=["max_level_debug"]}
tokio-tungstenite = "0.13"
thiserror = "1.0"
headers = "0.3"

[dev-dependencies]
env_logger = "0.8"
hyper = {version="0.14", features=["server", "http1", "http2", "tcp"]}
tokio = {version="1.2", features=["macros", "io-util", "fs"]}