name: Fork auto synchronization
on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Jan Gorkiewicz'
          git config --global user.email 'greencashew@users.noreply.github.com'

          git remote set-url origin "https://$GITHUB_ACTOR:${{ secrets.FORK_SYNC_TOKEN }}@github.com/$GITHUB_REPOSITORY"

          git remote add tmp_upstream "https://github.com/izderadicka/audioserve.git"

          echo "Fetching tmp_upstream"
          git fetch tmp_upstream --quiet
          git remote --verbose
          git rebase tmp_upstream/master
          git push origin

          git tag -d $(git tag -l) > /dev/null
          git fetch tmp_upstream --tags --quiet
          git push origin --tags --force

          echo "Removing tmp_upstream"
          git remote rm tmp_upstream
          git remote --verbose