name: Fork auto synchronisation

on:
  schedule:
    - cron: '0 * 0 ? * * *'

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: TG908/fork-sync@v1.1
        with:
          github_token: ${{ secrets.FORK_SYNC_TOKEN }}
          base: master
          head: master