name: Publish release on docker

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get release version
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
      - name: Test if tag retrived 
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Install buildx
          id: buildx
          uses: crazy-max/ghaction-docker-buildx@v1
          with:
            version: latest
      - name: Login to docker hub
          run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and Publish on docker hub
          run: |
              docker buildx build --push \
              --tag greencashew/audioserve:${{ env.RELEASE_VERSION }}
              --platform linux/amd64,linux/arm/v7,linux/arm64 . 
