name: Publish on docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Build and Publish on docker
        run: |
          docker buildx build \
            --tag greencashew/audioserve:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 . 
